[project]
name = "langgraph-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.0",
    "langgraph>=0.6.2",
    "matplotlib>=3.10.5",
    "networkx>=3.5",
]
